### ISSUE TITLE
Can't launch the app

### ISSUE THREAD

**Issue by dmitriyshashkin** [jangxx/SchubsiGo#6]
I tried to use your great app on Fedora 31 by downloading pre-built version from release. That's what I get when I try to launch it:

````
2020/05/06 12:46:23 Server is listening on localhost:33322
2020/05/06 12:46:23 Error while fetching old messages: Not logged in
2020/05/06 12:46:23 Not logged in
2020/05/06 12:46:23 Error was not network related, retry when we get the instruction. Error type: *errors.errorString
2020/05/06 12:46:23 Server exited with error: listen tcp 127.0.0.1:33322: bind: address already in use

(SchubsiGo:523708): Gtk-CRITICAL **: 12:46:23.228: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
```

Perhaps my distro is the problem. As I understand it GNOME 3.26 and later don't have a system tray anymore. Perhaps you could suggest some workaround?

**Comment by jangxx** [comment]
I don't have a workaround in mind tbh. Of course I could add something like a `--no-tray` switch for you, but then how would you open the settings interface? If you personally use a desktop environment without a system tray, you are probably in a better position to suggest new ideas than I am. We could start with the question: How are other applications handling this, like Steam, Franz, Guake Terminal, etc? Do they always show up as a full and proper window? Is the tray icon just gone and you have no way to access the functionality that you would usually get to through the tray icon? If GNOME offers a replacement for the tray, I could look into supporting that as well of course.

**Comment by dmitriyshashkin** [comment]
As I understood GNOME devs think that system tray is a bad design decision and simply wastes screen space. There are lots of discussions on this topic on Reddit and other places. Skype, for example just works in the background, if you want to perform some action, you just click the icon in apps/favorites. The app can use notifications to inform about a change of status, but there is nothing that would be similar to the classical tray icons.

As for the workaround: if you store settings in some simple format I can just enter the required configuration in the config file using vim, then launch the app with `--no-tray`. I know both the secret token and the device token (it's quite easy to obtain them from pushover web app).

**Comment by jangxx** [comment]
You wouldn't even have to edit the settings file by hand (even though it's just a json file), since the settings interface is simply a local webpage, so you could just connect to localhost:33322 and do the login procedure there. I guess that sounds like a good idea then - add a flag to disable the tray icon and maybe display an info box to the user, which tells them about the webinterface.

**Comment by dmitriyshashkin** [comment]
Visited localhost:33322, filled in the details and it seems that now I get the notifications. The program still outputs `Gtk-CRITICAL **: 15:21:57.828: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed` but the notifications appear as they should. The program doesn't demonize (not sure if that's expected) but in general, I consider it a success! The additional flag that would remove the error message would be cool, but perhaps the description of the workaround for GNOME users would suffice. Thank you! You've made my life a tad easier)

**Comment by jangxx** [comment]
Oh great, that good to hear. The program actually does not deamonize, so that is to be expected. If you want to run it as a deamon you can use systemd for example. I will add the flag and the necessary documentation in the coming days.

**Comment by jangxx** [comment]
Okay, I added the flag as well as some other minor improvements. Try out version 1.2.0 to see if your problems are fixed now.
